version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: github.com/hashicorp/terraform
    versions:
    - 0.14.5
    - 0.14.6
    - 0.14.7
